# Configuracoes do Servidor
server.port=8080

# Perfil ativo (dev, prod, etc)
spring.profiles.active=dev

# Configuracoes do Banco de Dados PostgreSQL
# Valores sensiveis sao buscados das variaveis de ambiente
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/water_tariff}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuracoes de Inicializacao SQL
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true